### ISSUE TITLE
Einheiten-Grafiken verbessern

### ISSUE THREAD

**Issue by Zocker1999NET** [HGE-IT-Course-2016/zweiundvierzig#100]
Die Einheiten-Grafiken müssen noch bis zur Präsentation zwingend verbessert werden. Zurzeit ist nicht leicht erkennbar, welche Farbe diese Einheiten haben.

_Der Pull Request mit den Verbesserungen geht zum Branch_ **master**.

**Comment by aaronholz** [comment]
Bilder erneuert
