### ISSUE TITLE
Einheitenverteilung bei 6 Spielern

### ISSUE THREAD

**Issue by SariusRu** [HGE-IT-Course-2016/zweiundvierzig#70]
Die Verteilung der Einheiten ist bei 6 Spielern noch nicht implementiert. Das von Max erwähnte Problem sollte auch nicht mehr bestehen.

**Comment by Zocker1999NET** [comment]
Wird geschlossen, da der Aufwand zu hoch ist, eine Verteilung für 6 Spieler auszudenken, da es im Original keine Verteilung gibt.
